# .github/workflows/dbt-ci.yml
name: CI

on:
  push:
    branches:
      - master

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Install dbt
        run: pip install dbt-core==1.9.4 dbt-postgres==1.9.0

      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          project_dw:
            target: prd
            outputs:
              prd:
                type: postgres
                threads: 4
                host: ${{ secrets.RENDER_DB_HOST }}
                user: ${{ secrets.RENDER_DB_USER }}
                pass: ${{ secrets.RENDER_DB_PASS }}
                port: ${{ secrets.RENDER_DB_PORT }}
                dbname: ${{ secrets.RENDER_DB_NAME }}
                schema: public
          EOF

      - name: dbt deps
        working-directory: project_dw
        run: dbt deps --profiles-dir ~/.dbt


      - name: dbt build
        working-directory: project_dw
        run: dbt build --profiles-dir ~/.dbt